import { describe, it, expect, beforeEach, vi } from "vitest";
import { render, screen } from "@testing-library/react";

const { listLayouts } = vi.hoisted(() => ({ listLayouts: vi.fn() }));

vi.mock("@/lib/api", () => ({
  projectsApi: {},
  sessionsApi: {},
  chatApi: {},
  workspaceApi: { listLayouts },
  workbenchApi: {},
}));

// The GDS→SVG viewer is irrelevant here; stub it so only the empty-state copy
// branches are exercised.
vi.mock("@/components/artifacts/LayoutViewer", () => ({
  LayoutViewer: () => <div>layout-viewer</div>,
}));

import { useStore } from "@/lib/store";
import { LayoutArtifact } from "@/components/workbench/viewers/LayoutArtifact";

const SESSION = { id: "s1", name: "s1", model_name: "x", project_id: null, created_at: null, updated_at: null, total_tokens: 0, total_cost: 0 };

beforeEach(() => {
  listLayouts.mockReset();
  useStore.setState({ currentSession: SESSION as any } as any);
});

describe("LayoutArtifact honest missing-binary copy (A7 / §3D)", () => {
  it("shows the fetch/re-run message when a GDS is split out but absent", async () => {
    listLayouts.mockResolvedValue({
      layouts: [],
      missing_binaries: ["synth_runs/synth_0001/orfs_results/sky130hd/top/base/6_final.gds"],
    });
    render(<LayoutArtifact runId="synth_0001" />);
    expect(await screen.findByText("GDS not present")).toBeInTheDocument();
    expect(screen.getByText(/fetch the example binaries/)).toBeInTheDocument();
  });

  it("shows the never-produced message when nothing is listed or missing", async () => {
    listLayouts.mockResolvedValue({ layouts: [], missing_binaries: [] });
    render(<LayoutArtifact runId="synth_0001" />);
    expect(await screen.findByText("No layout generated by this run")).toBeInTheDocument();
    expect(screen.queryByText(/fetch the example binaries/)).toBeNull();
  });
});
