"use client";

import { useCallback, useEffect, useState } from "react";
import { Layers } from "lucide-react";
import { useStore } from "@/lib/store";
import { workspaceApi } from "@/lib/api";
import { LayoutViewer } from "@/components/artifacts/LayoutViewer";
import { ViewerEmpty, ViewerError, ViewerSkeleton } from "./panels";

interface ResolveState {
  status: "loading" | "ready" | "none" | "error";
  filename: string | null;
  error: string | null;
  // GDS the split manifest lists but that is absent on disk — distinguishes
  // "not fetched" from "never produced" for the empty-state copy.
  missingBinaries: boolean;
}

/**
 * v2 tab wrapper for `layout:<runId>` — resolves the run's GDS by listing the
 * workspace layouts (prefer a path under synth_runs/<runId>/, else the newest
 * .gds) and renders the existing LayoutViewer pinned to that file.
 */
export function LayoutArtifact({ runId }: { runId: string }) {
  const sessionId = useStore((s) => s.currentSession?.id ?? null);
  const [state, setState] = useState<ResolveState>({
    status: "loading",
    filename: null,
    error: null,
    missingBinaries: false,
  });

  const resolve = useCallback(async () => {
    if (!sessionId) return;
    setState((s) => (s.filename ? s : { status: "loading", filename: null, error: null, missingBinaries: false }));
    try {
      const { layouts, missing_binaries } = await workspaceApi.listLayouts(sessionId);
      const gds = layouts.filter((f) => f.toLowerCase().endsWith(".gds"));
      const match =
        layouts.find((f) => f.includes(`synth_runs/${runId}/`)) ?? gds[0] ?? null;
      setState(
        match
          ? { status: "ready", filename: match, error: null, missingBinaries: false }
          : { status: "none", filename: null, error: null, missingBinaries: (missing_binaries?.length ?? 0) > 0 }
      );
    } catch (e) {
      setState({
        status: "error",
        filename: null,
        error: e instanceof Error ? e.message : String(e),
        missingBinaries: false,
      });
    }
  }, [sessionId, runId]);

  useEffect(() => {
    void resolve();
  }, [resolve]);

  if (state.status === "loading") return <ViewerSkeleton />;
  if (state.status === "error") {
    return <ViewerError title="Couldn't list layouts" detail={state.error} onRetry={() => void resolve()} />;
  }
  if (state.status === "none" || !state.filename) {
    return (
      <ViewerEmpty
        icon={<Layers />}
        title={state.missingBinaries ? "GDS not present" : "No layout generated by this run"}
        detail={
          state.missingBinaries
            ? "This example's layout binary isn't here — re-run synthesis, or fetch the example binaries."
            : "The GDS appears here once the OpenROAD flow finishes place & route for this run."
        }
      />
    );
  }

  return <LayoutViewer filename={state.filename} runId={runId} />;
}
