#!/usr/bin/env python
"""Split heavy, regenerable PnR binaries out of the committed example bundles.

    python -m scripts.split_bundle_binaries --dry-run          # inventory only
    python -m scripts.split_bundle_binaries --apply            # delete + manifest

A template bundle (``examples/<id>/``) ships real, readable designs in git —
RTL/spec/tb, run metadata, reports, logs, transcripts. What it must NOT drag
into every clone is the heavy, byte-for-byte regenerable OpenROAD output: the
final ``.gds``/``.def``/``.spef``/``.rtlil``, the synthesized gate-level ``.v``
netlists under ``orfs_results/``, and the rendered ``.webp`` layout previews.
Those are re-fetched from the public templates bucket (``fetch_examples.py``)
or regenerated by re-running synthesis.

This is a STRICTER filter than ``templates._prune_pnr_intermediates`` (which
drops only ``.odb`` + intermediate ``.gds``) — do not confuse them. The split
line is deliberately by file TYPE inside the two result trees, so that the
lightweight stage-completion markers (``.sdc``/``.json``/``.guide``/``.tcl``/
``.txt`` under ``orfs_results``; ``.rpt``/``.txt`` under ``orfs_reports``) stay
in git and ``get_stage_status``/``get_ppa``/the design report remain
byte-identical on a self-host clone that never fetched the binaries.

For each bundle that has any classified binary, ``--apply`` writes
``workspace/.sc_binaries.json`` = ``{"version":1,"files":[{"path","bytes",
"sha256"}]}`` (workspace-relative, forward-slash paths, deterministic order)
and deletes the classified files from the working tree. Git history preserves
them; the publish runbook reads the binaries from a pre-split ref. A bundle
with no ``orfs_results``/``orfs_reports`` payload (e.g. ``sync_fifo``) is left
untouched — no manifest, no deletions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from typing import List, Optional, Tuple

WORKSPACE_SUBDIR = "workspace"
SC_BINARIES_NAME = ".sc_binaries.json"
SC_BINARIES_VERSION = 1

# Heavy, regenerable result TYPES moved out of git. Keyed by the result tree
# they live under so a same-extension file elsewhere in the workspace (e.g. an
# RTL ``.v`` under ``inputs/`` or the repo source) is never touched.
_ORFS_RESULTS_DIR = "orfs_results"
_ORFS_REPORTS_DIR = "orfs_reports"
_RESULTS_BINARY_EXTS = {".gds", ".def", ".spef", ".rtlil", ".v"}
_REPORTS_BINARY_EXTS = {".webp"}


def is_binary(rel_path: str) -> bool:
    """True if a workspace-relative path is a heavy binary to move to GCS.

    ``rel_path`` uses forward slashes (workspace-relative). Classification is by
    directory membership + extension, never by filename, so the rule is stable
    across the ``orfs_results/<platform>/<top>/base/`` nesting.
    """
    parts = rel_path.split("/")
    ext = os.path.splitext(parts[-1])[1].lower()
    if _ORFS_RESULTS_DIR in parts[:-1] and ext in _RESULTS_BINARY_EXTS:
        return True
    if _ORFS_REPORTS_DIR in parts[:-1] and ext in _REPORTS_BINARY_EXTS:
        return True
    return False


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def inventory_workspace(ws: str) -> List[dict]:
    """Classified binaries under ``ws`` as sorted ``{path,bytes,sha256}`` dicts.

    Deterministic: sorted by workspace-relative path. The manifest file itself
    is never classified (it is not a binary and may not exist yet).
    """
    entries: List[dict] = []
    for root, _dirs, files in os.walk(ws):
        for name in files:
            abs_path = os.path.join(root, name)
            rel = os.path.relpath(abs_path, ws).replace(os.sep, "/")
            if rel == SC_BINARIES_NAME:
                continue
            if not is_binary(rel):
                continue
            entries.append(
                {"path": rel, "bytes": os.path.getsize(abs_path), "sha256": _sha256(abs_path)}
            )
    entries.sort(key=lambda e: e["path"])
    return entries


def split_bundle(bundle_dir: str, *, apply: bool) -> List[dict]:
    """Inventory (and, with ``apply``, delete + manifest) one bundle's binaries.

    Returns the classified entries (empty for a bundle with no payload). With
    ``apply`` and a non-empty inventory: writes ``workspace/.sc_binaries.json``
    then deletes the classified files. A bundle with no binaries is left exactly
    as-is (returns ``[]``, writes nothing).
    """
    ws = os.path.join(bundle_dir, WORKSPACE_SUBDIR)
    if not os.path.isdir(ws):
        return []
    entries = inventory_workspace(ws)
    if not entries or not apply:
        return entries

    manifest = {"version": SC_BINARIES_VERSION, "files": entries}
    with open(os.path.join(ws, SC_BINARIES_NAME), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    for entry in entries:
        os.remove(os.path.join(ws, entry["path"].replace("/", os.sep)))
    return entries


def _iter_bundles(examples_dir: str, only: Optional[str]) -> List[Tuple[str, str]]:
    out: List[Tuple[str, str]] = []
    for entry in sorted(os.scandir(examples_dir), key=lambda e: e.name):
        if not entry.is_dir():
            continue
        if only and entry.name != only:
            continue
        out.append((entry.name, entry.path))
    return out


def _default_examples_dir() -> str:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(repo_root, "examples")


def _fmt_mb(n: int) -> str:
    return f"{n / (1024 * 1024):.2f} MB"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Split heavy PnR binaries out of examples/ bundles (see module docstring)."
    )
    parser.add_argument(
        "--examples-dir", default=_default_examples_dir(), help="Bundles root (default: ./examples)."
    )
    parser.add_argument("--bundle", default=None, help="Only this bundle id (default: all).")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--dry-run", action="store_true", help="Print the inventory + totals; change nothing (default)."
    )
    mode.add_argument(
        "--apply", action="store_true", help="Write .sc_binaries.json and DELETE the classified files."
    )
    args = parser.parse_args(argv)

    examples_dir = os.path.abspath(args.examples_dir)
    if not os.path.isdir(examples_dir):
        print(f"error: examples dir not found: {examples_dir}", file=sys.stderr)
        return 2

    grand_files = 0
    grand_bytes = 0
    touched = 0
    for name, bundle_dir in _iter_bundles(examples_dir, args.bundle):
        entries = split_bundle(bundle_dir, apply=args.apply)
        if not entries:
            print(f"{name}: no binaries (left untouched)")
            continue
        touched += 1
        b = sum(e["bytes"] for e in entries)
        grand_files += len(entries)
        grand_bytes += b
        verb = "moved" if args.apply else "would move"
        print(f"{name}: {verb} {len(entries)} file(s), {_fmt_mb(b)}")
        if args.dry_run or not args.apply:
            for e in entries:
                print(f"    {e['path']}  ({e['bytes']} bytes)")

    verb = "Applied" if args.apply else "Dry-run"
    print(
        f"\n{verb}: {touched} bundle(s), {grand_files} file(s), {_fmt_mb(grand_bytes)} total."
    )
    if not args.apply:
        print("(no changes written — pass --apply to delete + write .sc_binaries.json)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
