#!/usr/bin/env python3
"""Generate a bench-orchestrator YAML config from a raw CVDP dataset.

This replaces the old prepare/extract/prompt-list flow. The bench-orchestrator
(`kind: cvdp_agentic_jsonl`) reads the raw CVDP JSONL directly by `datapoint_id`
and materializes context/harness/problem.json itself at run time, so this script
only needs to *select* problems and emit a valid config.

Usage:
    python cvdp-pipeline/generate_cvdp_config.py \
        --dataset cvdp_benchmark/data/cvdp_v1.0.2_agentic_code_generation_no_commercial.jsonl \
        --out bench-orchestrator/configs/cvdp_des_smoke.yaml \
        --ids cvdp_agentic_DES_0001

    # or select by category / count
    python cvdp-pipeline/generate_cvdp_config.py --dataset <raw.jsonl> --out <cfg.yaml> \
        --category cid003 --max-problems 5
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Optional

import yaml

# Repo root = parent of the cvdp-pipeline/ directory this file lives in.
REPO_ROOT = Path(__file__).resolve().parent.parent


def _looks_commercial_name(name: str) -> bool:
    s = (name or "").lower()
    return ("commercial" in s) and ("no_commercial" not in s)


def load_rows(dataset: Path) -> List[dict]:
    rows: List[dict] = []
    with dataset.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            s = line.strip()
            if not s:
                continue
            try:
                rows.append(json.loads(s))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at line {i} of {dataset}: {exc}") from exc
    return rows


def short_id(datapoint_id: str) -> str:
    """Derive a short, filesystem/run-dir-friendly problem id from the datapoint id."""
    s = re.sub(r"^cvdp_(agentic|nonagentic)_", "", datapoint_id)
    s = re.sub(r"[^A-Za-z0-9_-]+", "_", s).strip("_").lower()
    return s or datapoint_id.lower()


def select_rows(
    rows: List[dict],
    ids: Optional[List[str]],
    category: Optional[str],
    max_problems: int,
) -> List[dict]:
    if ids:
        wanted = list(ids)
        by_id = {str(r.get("id")): r for r in rows}
        missing = [i for i in wanted if i not in by_id]
        if missing:
            raise ValueError(f"Datapoint id(s) not found in dataset: {', '.join(missing)}")
        return [by_id[i] for i in wanted]  # preserve requested order

    selected = rows
    if category:
        cat = category.strip().lower()
        selected = [r for r in selected if cat in [str(c).lower() for c in (r.get("categories") or [])]]
    if max_problems and max_problems > 0:
        selected = selected[:max_problems]
    return selected


def dataset_path_for_yaml(dataset: Path) -> str:
    """Express the dataset path repo-relative (POSIX) so the bench config resolves it."""
    resolved = dataset.resolve()
    try:
        return resolved.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return resolved.as_posix()


def build_config(
    rows: List[dict],
    name: str,
    dataset_yaml: str,
    agent: str,
    model: str,
    flow: str,
    mcp_server: str,
    timeout: int,
    project_name: str,
    project_enabled: bool,
) -> dict:
    seen: Dict[str, int] = {}
    problems = []
    for r in rows:
        did = str(r["id"])
        sid = short_id(did)
        # Guard against collisions after shortening.
        if sid in seen:
            seen[sid] += 1
            sid = f"{sid}_{seen[sid]}"
        else:
            seen[sid] = 0
        problems.append(
            {
                "id": sid,
                "suite": "cvdp",
                "kind": "cvdp_agentic_jsonl",
                "dataset": dataset_yaml,
                "datapoint_id": did,
            }
        )
    return {
        "name": name,
        "project": {"enabled": project_enabled, "name": project_name},
        "defaults": {
            "agent": agent,
            "model": model,
            "flow": flow,
            "mcp_server": mcp_server,
            "timeout_sec": timeout,
            "evaluation": "cvdp_replay_harness",
        },
        "problems": problems,
    }


_HEADER = (
    "# Generated by cvdp-pipeline/generate_cvdp_config.py — do not hand-edit problem ids.\n"
    "# CVDP is RTL-simulation-only: the verilog flow + cvdp_agentic_jsonl kind instruct the\n"
    "# agent to skip synthesis/PD. Grade in the reference container with\n"
    "#   cvdp-pipeline/regrade_docker.py --run-dir <run>   (needs Docker + the osvb image).\n"
    "# NOTE: for real (non-fake) agents, export RTL_WORKSPACE so the orchestrator's workspace\n"
    "#       discovery matches where the rtl-codex MCP server writes sessions (its .env root).\n"
)


def dump_yaml(config: dict) -> str:
    body = yaml.safe_dump(config, sort_keys=False, default_flow_style=False, width=120)
    return _HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a bench-orchestrator YAML from a raw CVDP dataset.")
    ap.add_argument("--dataset", required=True, help="Raw CVDP JSONL (with context/harness/patch fields).")
    ap.add_argument("--out", required=True, help="Output YAML path (e.g. bench-orchestrator/configs/cvdp_x.yaml).")
    ap.add_argument("--ids", default="", help="Comma-separated datapoint ids to include (overrides category/max).")
    ap.add_argument("--category", default="", help="Select datapoints whose categories list contains this value (e.g. cid003).")
    ap.add_argument("--max-problems", type=int, default=0, help="Limit number of problems (0 = all matched).")
    ap.add_argument("--name", default="", help="Benchmark name (default derived from output filename).")
    ap.add_argument("--project-name", default="", help="SiliconCrew project name (default bench_<name>).")
    ap.add_argument("--agent", default="fake", help="Default agent (fake|codex|claude|antigravity).")
    ap.add_argument("--model", default="gpt-5.5", help="Default model.")
    ap.add_argument("--flow", default="verilog", help="Flow (verilog for CVDP RTL-only).")
    ap.add_argument("--mcp-server", default="rtl-codex", help="MCP server name.")
    ap.add_argument("--timeout", type=int, default=2400, help="Per-problem timeout seconds.")
    ap.add_argument("--allow-commercial", action="store_true", help="Allow commercial datasets (xrun-dependent). Default: reject.")
    ap.add_argument(
        "--enable-project",
        action="store_true",
        help="Group sessions under a SiliconCrew project. Default off: the orchestrator and the "
        "MCP server can use different session DBs, so a project_id would fail 'Project not found'.",
    )
    args = ap.parse_args()

    dataset = Path(args.dataset)
    if not dataset.exists():
        raise FileNotFoundError(f"Dataset not found: {dataset}")
    if not args.allow_commercial and _looks_commercial_name(dataset.name):
        raise ValueError(
            f"Commercial dataset detected ({dataset.name}); these need xrun/Cadence infra. "
            "Use a no_commercial dataset or pass --allow-commercial."
        )

    out = Path(args.out)
    name = args.name.strip() or out.stem
    project_name = args.project_name.strip() or f"bench_{name}"

    rows = load_rows(dataset)
    ids = [s.strip() for s in args.ids.split(",") if s.strip()] or None
    selected = select_rows(rows, ids, args.category or None, args.max_problems)
    if not selected:
        raise ValueError("No problems matched the selection criteria.")

    config = build_config(
        rows=selected,
        name=name,
        dataset_yaml=dataset_path_for_yaml(dataset),
        agent=args.agent,
        model=args.model,
        flow=args.flow,
        mcp_server=args.mcp_server,
        timeout=args.timeout,
        project_name=project_name,
        project_enabled=bool(args.enable_project),
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dump_yaml(config), encoding="utf-8", newline="\n")
    print(f"Wrote {len(selected)} problem(s) to: {out}")
    for p in config["problems"]:
        print(f"  - {p['id']:<32} <- {p['datapoint_id']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
