import os
import subprocess
from .run_docker import run_docker_command

def generate_schematic(verilog_file, top_module, cwd=None):
    """
    Generates an SVG schematic from a Verilog file using Yosys and NetlistSVG.
    
    Args:
        verilog_file (str): Absolute path to the Verilog file.
        top_module (str): Name of the top-level module.
        cwd (str): Workspace directory.
        
    Returns:
        dict: {
            "success": bool,
            "svg_path": str, # Path to generated SVG
            "error": str
        }
    """
    if cwd is None:
        cwd = os.path.dirname(verilog_file)
        
    # 1. Generate JSON using Yosys (Docker)
    # We need to map the file to the container path
    if cwd in verilog_file:
        rel_path = os.path.relpath(verilog_file, cwd).replace("\\", "/")
        container_input = f"/workspace/{rel_path}"
    else:
        container_input = f"/workspace/{os.path.basename(verilog_file)}"
        
    json_filename = f"{top_module}_schematic.json"
    svg_filename = f"{top_module}_schematic.svg"
    
    container_json_output = f"/workspace/{json_filename}"
    
    # Yosys command: Hierarchy -> Proc -> Opt -> Write JSON
    yosys_cmd = f"yosys -p 'read_verilog {container_input}; hierarchy -top {top_module}; proc; opt; write_json {container_json_output}'"
    
    print(f"[SCHEM] Generating Schematic JSON for {top_module}...")
    result = run_docker_command(command=yosys_cmd, workspace_path=cwd)
    
    if not result['success']:
        return {"success": False, "error": f"Yosys Failed: {result['stderr']}"}
        
    # 2. Generate SVG using NetlistSVG (Local Node.js)
    local_json_path = os.path.join(cwd, json_filename)
    local_svg_path = os.path.join(cwd, svg_filename)
    
    if not os.path.exists(local_json_path):
        return {"success": False, "error": "JSON file was not generated by Yosys."}
        
    print(f"[RENDER] Rendering SVG using NetlistSVG...")
    try:
        # npx -y netlistsvg input.json -o output.svg
        cmd = ["npx", "-y", "netlistsvg", local_json_path, "-o", local_svg_path]
        
        # Run local command (shell=True for Windows npx resolution sometimes needed, but list is safer)
        # On Windows, npx might be a batch file, so shell=True might be needed or full path.
        # Let's try shell=True for npx on Windows.
        subprocess.run(cmd, cwd=cwd, check=True, shell=True, capture_output=True)
        
        if os.path.exists(local_svg_path):
            return {"success": True, "svg_path": local_svg_path}
        else:
            return {"success": False, "error": "NetlistSVG finished but SVG file not found."}
            
    except subprocess.CalledProcessError as e:
        return {"success": False, "error": f"NetlistSVG Failed: {e.stderr.decode() if e.stderr else str(e)}"}
    except Exception as e:
        return {"success": False, "error": f"SVG Generation Error: {str(e)}"}
